name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            -r requirements.txt \
            -r flatmates_bill/requirements.txt \
            -r math_painting/requirements.txt \
            -r photo_searcher/requirements.txt

      - name: Run tests
        run: |
          python3 -m pytest -v
