name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-dev build-essential libgl1-mesa-dev \
            libgles2-mesa-dev zlib1g-dev gstreamer1.0-plugins-base \
            gstreamer1.0-plugins-good gstreamer1.0-plugins-bad  \
            gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc \
            gstreamer1.0-tools gstreamer1.0-x \
            gstreamer1.0-alsa gstreamer1.0-pulseaudio libmtdev-dev libglfw3-dev \
            libgstreamer-plugins-base1.0-dev
          sudo add-apt-repository universe
          sudo add-apt-repository multiverse
          sudo apt update
          sudo apt-get install xclip xsel

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install \
            -r requirements.txt \
            -r flatmates_bill/requirements.txt \
            -r math_painting/requirements.txt \
            -r photo_searcher/requirements.txt

      - name: Run tests
        run: |
          python3 -m pytest -v -o log_cli=true --log-level=DEBUG
